"use client";

import { useState, useTransition } from "react";
import { Download, LoaderCircle, ShieldAlert, Trash2 } from "lucide-react";
import { deleteAccountAction, exportAccountDataAction } from "@/modules/identity/application/account-actions";
import { revokeAiConsentAction } from "@/modules/reflection/application/reflection-actions";

export function AccountSettings({ locale, aiConsented }: { locale: "es" | "en"; aiConsented: boolean }) {
  const [pending, startTransition] = useTransition(); const [confirmation, setConfirmation] = useState(""); const [message, setMessage] = useState<string>(); const [error, setError] = useState<string>();
  const t = locale === "es" ? { eyebrow: "Control de datos", title: "Ajustes y privacidad", intro: "Tu historia es tuya. Aquí puedes llevártela contigo o eliminarla definitivamente.", export: "Exportar mis datos", exportBody: "Descarga un archivo JSON con tus experiencias, conexiones, genealogía, conversaciones y metadatos de adjuntos.", ai: "Consentimiento de IA", aiBody: "Puedes retirar el permiso de enviar el texto de tus experiencias al asistente en cualquier momento.", revoke: "Retirar consentimiento", danger: "Eliminar mi cuenta", dangerBody: "Borrará de forma irreversible tu cuenta, experiencias, conversaciones, familia y archivos. Escribe DELETE para confirmar.", remove: "Eliminar definitivamente", exported: "La exportación se ha descargado.", revoked: "El consentimiento de IA se ha retirado.", deleted: "Cuenta eliminada." } : { eyebrow: "Data control", title: "Settings and privacy", intro: "Your story is yours. Here you can take it with you or delete it forever.", export: "Export my data", exportBody: "Download a JSON file with your experiences, connections, family tree, conversations and attachment metadata.", ai: "AI consent", aiBody: "You can withdraw permission to send the text of your experiences to the assistant at any time.", revoke: "Withdraw consent", danger: "Delete my account", dangerBody: "This permanently erases your account, experiences, chats, family tree and files. Type DELETE to confirm.", remove: "Delete permanently", exported: "Your export has downloaded.", revoked: "AI consent has been withdrawn.", deleted: "Account deleted." };
  function exportData() { setError(undefined); startTransition(async () => { const result = await exportAccountDataAction(); if (!result.ok) { setError(result.error); return; } const blob = new Blob([JSON.stringify(result.data, null, 2)], { type: "application/json" }); const href = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = href; link.download = `your-life-story-export-${new Date().toISOString().slice(0, 10)}.json`; link.click(); URL.revokeObjectURL(href); setMessage(t.exported); }); }
  function revoke() { setError(undefined); startTransition(async () => { const result = await revokeAiConsentAction(locale); if (!result.ok) setError(result.error); else setMessage(t.revoked); }); }
  function remove() { setError(undefined); if (!window.confirm(t.dangerBody)) return; startTransition(async () => { const result = await deleteAccountAction(confirmation, locale); if (!result.ok) setError(result.error); else { setMessage(t.deleted); window.location.assign(`/${locale}`); } }); }
  return <div className="mx-auto max-w-3xl fade-in"><p className="eyebrow">{t.eyebrow}</p><h1 className="display mt-2 text-4xl sm:text-5xl">{t.title}</h1><p className="mt-3 text-sm leading-6 text-[var(--muted)]">{t.intro}</p><div className="mt-8 space-y-5"><section className="card p-6"><Download className="text-[var(--moss)]" size={21} /><h2 className="display mt-3 text-2xl">{t.export}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{t.exportBody}</p><button disabled={pending} className="btn btn-secondary mt-5" onClick={exportData}>{pending && <LoaderCircle className="animate-spin" size={15} />}<Download size={15} />{t.export}</button></section><section className="card p-6"><ShieldAlert className="text-[var(--moss)]" size={21} /><h2 className="display mt-3 text-2xl">{t.ai}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{t.aiBody}</p>{aiConsented ? <button disabled={pending} className="btn btn-secondary mt-5" onClick={revoke}>{t.revoke}</button> : <span className="pill mt-5">{locale === "es" ? "No hay consentimiento activo" : "No active consent"}</span>}</section><section className="card border-[#edcfcb] p-6"><Trash2 className="text-[var(--danger)]" size={21} /><h2 className="display mt-3 text-2xl">{t.danger}</h2><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{t.dangerBody}</p><input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="input mt-5 max-w-sm" placeholder="DELETE" /><button disabled={pending || confirmation !== "DELETE"} className="btn btn-danger mt-4" onClick={remove}>{pending && <LoaderCircle className="animate-spin" size={15} />}<Trash2 size={15} />{t.remove}</button></section>{error && <p className="field-error">{error}</p>}{message && <p className="rounded-xl bg-[#edf5ec] p-3 text-sm text-[var(--moss-deep)]">{message}</p>}</div></div>;
}
